Always add WWWAuthenticate header
unosquare/embedio pull request #515
Opened 2021-04-19 07:51 UTC by duddo

WWWAuthenticate header should be added to the answer, even if it's a 401. This way a browser can show the user/password form.

2021-04-19 08:09 UTC, rdeago commented
Hello @duddo, thanks for the PR. I've created a related issue for completeness.

2021-04-19 08:24 UTC, rdeago requested changes
The fix looks fine to me. Just put header checks in their own test methods and it's good to merge IMO.

2021-04-19 08:24 UTC, rdeago commented on test/EmbedIO.Tests/BasicAuthenticationModuleTest.cs
> +            Assert.AreEqual("Basic realm=\"/\" charset=UTF-8", response.Headers.WwwAuthenticate.ToString());
It's a good thing you added this check, but it should be in its own method, maybe named `RequestWithValidCredentials_ReturnsValidWWWAuthenticateHeader`.

2021-04-19 08:24 UTC, rdeago commented on test/EmbedIO.Tests/BasicAuthenticationModuleTest.cs
> +            Assert.AreEqual("Basic realm=\"/\" charset=UTF-8", response.Headers.WwwAuthenticate.ToString());
It's a good thing you added this check, but it should be in its own method, maybe named `RequestWithInvalidCredentials_ReturnsValidWWWAuthenticateHeader`.

2021-04-19 08:24 UTC, rdeago commented on test/EmbedIO.Tests/BasicAuthenticationModuleTest.cs
> +            Assert.AreEqual("Basic realm=\"/\" charset=UTF-8", response.Headers.WwwAuthenticate.ToString());
It's a good thing you added this check, but it should be in its own method, maybe named `RequestWithNoAuthorizationHeader_ReturnsValidWWWAuthenticateHeader`.

2021-04-19 12:39 UTC, rdeago commented
Closing because #517 has everything this PR has, plus suggested corrections.

2021-04-19 12:47 UTC, rdeago commented
Reopening because #517 targets another branch. My fault, sorry.

2021-04-19 13:18 UTC, duddo commented
Requested changed resolved.

2021-04-20 15:16 UTC, rdeago approved these changes

2021-04-21 14:01 UTC, geoperez approved these changes

2021-04-21 14:01 UTC, merged