PR with fixes of some issues
unosquare/embedio pull request #534
Opened 2021-10-29 22:36 UTC by radioegor146

This PR fixes #531, #528, #519, #504 and tests on GH Actions

2021-10-29 22:37 UTC, radioegor146 commented
@rdeago also, is there any possible time of release v4.0? Or I can continue to fix that library from the current state?

2022-01-11 16:31 UTC, rdeago requested changes
Great job @radioegor146! Please forgive me for taking so long to review.

Being a fan of simplification, I especially like `ListenerUri`. 😃 

Just remove the two added usings [here](https://github.com/unosquare/embedio/pull/534/files#diff-d050adcf0087ebd5cb8f9ce888f59375bd2c70f516a4eeb37da6edf8971dddb1) if they are not necessary. Otherwise, this PR is absolutely to be merged IMO.

2022-01-11 16:31 UTC, rdeago commented on README.md
> +    public class WebSocketsChatModule : WebSocketModule
Not really addressing an issue, but good for consistency anyway. 👍

2022-01-11 16:31 UTC, rdeago commented on src/packages/EmbedIO/Files/ZipFileProvider.cs
> +            ZipArchiveEntry entry = _zipArchive.GetEntry(path.Substring(1));
Why not just use `var`?

2022-01-11 16:31 UTC, rdeago commented on src/packages/EmbedIO/Net/Internal/SystemHttpResponse.cs
> +using System.Collections;
Are you sure these two added usings are necessary? You made no other changes to this file.

2022-01-18 20:28 UTC, radioegor146 commented
> Great job @radioegor146! Please forgive me for taking so long to review.
> 
> Being a fan of simplification, I especially like `ListenerUri`. 😃
> 
> Just remove the two added usings [here](https://github.com/unosquare/embedio/pull/534/files#diff-d050adcf0087ebd5cb8f9ce888f59375bd2c70f516a4eeb37da6edf8971dddb1) if they are not necessary. Otherwise, this PR is absolutely to be merged IMO.

I've fixed some changes. Also, the added `chcp` command is to make sure that `netsh` output is in the simplest possible encoding (CP437/OEM), just because on systems with other default regional settings (as mine - ru_RU), the error message is really unreadable.

2022-01-19 07:33 UTC, rdeago commented on src/packages/EmbedIO/Files/ZipFileProvider.cs
> +            ZipArchiveEntry entry = _zipArchive.GetEntry(path.Substring(1));
Solved in later commit. 👍

2022-01-19 07:34 UTC, rdeago commented on src/packages/EmbedIO/Net/Internal/SystemHttpResponse.cs
> +using System.Collections;
Solved in later commit. 👍

2022-01-19 07:37 UTC, rdeago approved these changes
Great job @radioegor146!

2022-01-19 08:28 UTC, rdeago commented
> @rdeago also, are there any plans or possible time of release v4.0? Or I can continue to fix that library/add new features from the current state?

Unfortunately, no 4.0 release in sight at the moment, but I'm going to submit a PR that backports your changes to the `v3.x` branch.

2022-01-19 08:28 UTC, merged

2022-01-20 16:54 UTC, dtsirkovmb commented
Hi @rdeago, do you have any idea when will backports to v3.x take place? Cheers.

2022-01-20 19:21 UTC, rdeago commented
@dtsirkovmb I'm on it. I also found a couple other things in need of a fix, the PR should be ready by Monday.